version: "3"
services:
    apache-php7:
        build: ./php
        container_name: "webservice"
        volumes:
            - ../html:/var/www/html
            - ./php/apache:/etc/apache2/sites-available
            - ./php/logs:/logs/apache
        ports:
            - 80:80
            - 443:443
        networks: 
            - mynetwork
        restart: always
        environment:
            APACHE_LOG_DIR: /logs/apache
networks: 
    mynetwork:
        driver: bridge